### ISSUE TITLE
ExpatError: XML or text declaration not at start of entity

### ISSUE THREAD

**Issue by pafcu** [maxcutler/python-wordpress-xmlrpc#12]
My server is running Wordpress 3.2.1.
The following code:

```
from wordpress_xmlrpc import Client
wp = Client('<redacted>', '<redacted>', '<redacted>')
```

results in the exception:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    wp = Client('<redacted>', '<redacted>', '<redacted>')
  File "/home/pafcu/projects/rsswp/wordpress_xmlrpc/base.py", line 24, in __init__
    self.supported_methods = self.server.mt.supportedMethods()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1570, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1462, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 2, column 0
```

It seems like the library has trouble with the whitespace at the beginning of the reply from the server.

**Comment by kiwiheretic** [comment]
I get this issue as well.  Have managed to capture the xml file on the return path.  It is as follows:

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param>
      <value>
      <array><data>
  <value><struct>
  <member><name>post_id</name><value><string>1914</string></value></member>
  <member><name>post_title</name><value><string>Logos Notes 16-Mar-2015</string></value></member>
  <member><name>post_date</name><value><dateTime.iso8601>20150317T13:21:22</dateTime.iso8601></value></member>
  <member><name>post_date_gmt</name><value><dateTime.iso8601>20150317T00:21:22</dateTime.iso8601></value></member>
  <member><name>post_modified</name><value><dateTime.iso8601>20150317T13:21:22</dateTime.iso8601></value></member>
  <member><name>post_modified_gmt</name><value><dateTime.iso8601>20150317T00:21:22</dateTime.iso8601></value></member>
  <member><name>post_status</name><value><string>draft</string></value></member>
  <member><name>post_type</name><value><string>post</string></value></member>
  <member><name>post_name</name><value><string></string></value></member>
  <member><name>post_author</name><value><string>1</string></value></member>
  <member><name>post_password</name><value><string></string></value></member>
  <member><name>post_excerpt</name><value><string></string></value></member>
  <member><name>post_content</name><value><string>This is an automatically generated post courtesy of the Wordpress plugin for Logos-v2 IRC by SplatsCreations.  Please see the website: http://github.com/kiwiheretic/logos-v2 for more information.&lt;br/&gt;
&lt;br/&gt;
[1] NASB Job 17:9 &quot;Nevertheless the righteous will hold to his way, And he who has clean hands will grow stronger and stronger.
&lt;br/&gt;
&lt;br/&gt;
&lt;br/&gt;
[1] NASB James 1:8 being a double-minded man, unstable in all his ways.
[2] NASB James 4:8 Draw near to God and He will draw near to you. Cleanse your hands, you sinners; and purify your hearts, you double-minded.
&lt;br/&gt;
We want to be strong enough to stand against the wiles of the devil
&lt;br/&gt;
[1] NASB Job 6:11 &quot;What is my strength, that I should wait? And what is my end, that I should endure?
&lt;br/&gt;
[1] NASB Hebrews 10:36 For you have need of endurance, so that when you have done the will of God, you may receive what was promised.
&lt;br/&gt;NASB Philippians 4:19 And my God will supply all your needs according to His riches in glory in Christ Jesus.
NASB Philippians 4:4 Rejoice in the Lord always; again I will say, rejoice!
NASB Philippians 4:5 Let your gentle spirit be known to all men. The Lord is near.
NASB Philippians 4:6 Be anxious for nothing, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.
NASB Philippians 4:7 And the peace of God, which surpasses all comprehension, will guard your hearts and your minds in Christ Jesus.
&lt;br/&gt;
[1] NASB Romans 9:23 And He did so to make known the riches of His glory upon vessels of mercy, which He prepared beforehand for glory,
[2] NASB Ephesians 1:18 I pray that the eyes of your heart may be enlightened, so that you will know what is the hope of His calling, what are the riches of the glory of His inheritance in the saints,
[3] NASB Ephesians 3:16 that He would grant you, according to the riches of His glory, to be strengthened with power through His Spirit in the inner man,
[4] NASB Philippians 4:19 And my God will supply all your needs according to His riches in glory in Christ Jesus.
NASB Ephesians 3:16 that He would grant you, according to the riches of His glory, to be strengthened with power through His Spirit in the inner man,
NASB Ephesians 3:17 so that Christ may dwell in your hearts through faith; and that you, being rooted and grounded in love,
NASB Ephesians 3:18 may be able to comprehend with all the saints what is the breadth and length and height and depth,
NASB Ephesians 3:19 and to know the love of Christ which surpasses knowledge, that you may be filled up to all the fullness of God.
NASB Ephesians 3:20 Now to Him who is able to do far more abundantly beyond all that we ask or think, according to the power that works within us,
NASB Ephesians 3:21 to Him be the glory in the church and in Christ Jesus to all generations forever and ever. Amen.

&lt;br/&gt;
notice that it says that God supplies our needs according to the riches of us giving Him glory, not according to the abundance of our prayers
&lt;br/&gt;
&lt;br/&gt;
[1] NASB 2 Corinthians 1:11 you also joining in helping us through your prayers, so that thanks may be given by many persons on our behalf for the favor bestowed on us through the prayers of many.
&lt;br/&gt;
[1] NASB Hebrews 5:7 In the days of His flesh, He offered up both prayers and supplications with loud crying and tears to the One able to save Him from death, and He was heard because of His piety.
&lt;br/&gt;
NASB 1 John 5:14 This is the confidence which we have before Him, that, if we ask anything according to His will, He hears us.
NASB 1 John 5:15 And if we know that He hears us in whatever we ask, we know that we have the requests which we have asked from Him.
NASB 1 John 5:16 If anyone sees his brother committing a sin not leading to death, he shall ask and God will for him give life to those who commit sin not leading to death. There is a sin leading to death; I do not say that he should make request for this.
NASB 1 John 5:17 All unrighteousness is sin, and there is a sin not leading to death.

NASB Psalms 105:4 Seek the LORD and His strength; Seek His face continually.
&lt;br/&gt;
Seek God's strength 

NASB Psalms 106:3 How blessed are those who keep justice, Who practice righteousness at all times!

Practice righteousness.  Be a doer not a hearer only.   See also John 3:21</string></value></member>
  <member><name>post_parent</name><value><string>0</string></value></member>
  <member><name>post_mime_type</name><value><string></string></value></member>
  <member><name>link</name><value><string>http://www.splats-world.pw/?p=1914</string></value></member>
  <member><name>guid</name><value><string>http://www.splats-world.pw/?p=1914</string></value></member>
  <member><name>menu_order</name><value><int>0</int></value></member>
  <member><name>comment_status</name><value><string>closed</string></value></member>
  <member><name>ping_status</name><value><string>open</string></value></member>
  <member><name>sticky</name><value><boolean>0</boolean></value></member>
  <member><name>post_thumbnail</name><value><array><data>
</data></array></value></member>
  <member><name>post_format</name><value><string>standard</string></value></member>
  <member><name>terms</name><value><array><data>
</data></array></value></member>
  <member><name>custom_fields</name><value><array><data>
</data></array></value></member>
</struct></value>
  <value><struct>
  <member><name>post_id</name><value><string>1900</string></value></member>
  <member><name>post_title</name><value><string>Sermon Notes 15-Mar-2015</string></value></member>
  <member><name>post_date</name><value><dateTime.iso8601>20150317T13:17:59</dateTime.iso8601></value></member>
  <member><name>post_date_gmt</name><value><dateTime.iso8601>20150317T00:17:59</dateTime.iso8601></value></member>
  <member><name>post_modified</name><value><dateTime.iso8601>20150317T13:17:59</dateTime.iso8601></value></member>
  <member><name>post_modified_gmt</name><value><dateTime.iso8601>20150317T00:17:59</dateTime.iso8601></value></member>
  <member><name>post_status</name><value><string>draft</string></value></member>
  <member><name>post_type</name><value><string>post</string></value></member>
  <member><name>post_name</name><value><string></string></value></member>
  <member><name>post_author</name><value><string>1</string></value></member>
  <member><name>post_password</name><value><string></string></value></member>
  <member><name>post_excerpt</name><value><string></string></value></member>
  <member><name>post_content</name><value><string>This is an automatically generated post courtesy of the Wordpress plugin for Logos-v2 IRC by SplatsCreations.  Please see the website: http://github.com/kiwiheretic/logos-v2 for more information.&lt;br/&gt;
&lt;br/&gt;
The glory days of churchianity are coming to an end
&lt;br/&gt;
 Jude
NASB Jude 1:24 Now to Him who is able to keep you from stumbling, and to make you stand in the presence of His glory blameless with great joy,
NASB Jude 1:23 save others, snatching them out of the fire; and on some have mercy with fear, hating even the garment polluted by the flesh.
NASB John 4:16 He *said to her, &quot;Go, call your husband and come here.&quot;
NASB John 4:1 Therefore when the Lord knew that the Pharisees had heard that Jesus was making and baptizing more disciples than John
NASB John 4:2 (although Jesus Himself was not baptizing, but His disciples were),
NASB John 4:3 He left Judea and went away again into Galilee.
NASB John 4:4 And He had to pass through Samaria.
NASB John 4:5 So He *came to a city of Samaria called Sychar, near the parcel of ground that Jacob gave to his son Joseph;
NASB John 4:6 and Jacob's well was there. So Jesus, being wearied from His journey, was sitting thus by the well. It was about the sixth hour.
NASB John 4:7 There *came a woman of Samaria to draw water. Jesus *said to her, &quot;Give Me a drink.&quot;
NASB John 4:8 For His disciples had gone away into the city to buy food.
NASB John 4:9 Therefore the Samaritan woman *said to Him, &quot;How is it that You, being a Jew, ask me for a drink since I am a Samaritan woman?&quot; (For Jews have no dealings with Samaritans.)
NASB John 4:10 Jesus answered and said to her, &quot;If you knew the gift of God, and who it is who says to you, 'Give Me a drink,' you would have asked Him, and He would have given you living water.&quot;
NASB John 4:11 She *said to Him, &quot;Sir, You have nothing to draw with and the well is deep; where then do You get that living water?
NASB John 4:12 &quot;You are not greater than our father Jacob, are You, who gave us the well, and drank of it himself and his sons and his cattle?&quot;
NASB John 4:13 Jesus answered and said to her, &quot;Everyone who drinks of this water will thirst again;
NASB John 4:14 but whoever drinks of the water that I will give him shall never thirst; but the water that I will give him will become in him a well of water springing up to eternal life.&quot;
NASB John 4:15 The woman *said to Him, &quot;Sir, give me this water, so I will not be thirsty nor come all the way here to draw.&quot;
NASB John 4:16 He *said to her, &quot;Go, call your husband and come here.&quot;
NASB John 4:17 The woman answered and said, &quot;I have no husband.&quot; Jesus *said to her, &quot;You have correctly said, 'I have no husband';
NASB John 4:18 for you have had five husbands, and the one whom you now have is not your husband; this you have said truly.&quot;
NASB John 4:19 The woman *said to Him, &quot;Sir, I perceive that You are a prophet.
NASB John 4:20 &quot;Our fathers worshiped in this mountain, and you people say that in Jerusalem is the place where men ought to worship.&quot;
NASB John 4:21 Jesus *said to her, &quot;Woman, believe Me, an hour is coming when neither in this mountain nor in Jerusalem will you worship the Father.
NASB John 4:22 &quot;You worship what you do not know; we worship what we know, for salvation is from the Jews.
NASB John 4:23 &quot;But an hour is coming, and now is, when the true worshipers will worship the Father in spirit and truth; for such people the Father seeks to be His worshipers.
NASB John 4:24 &quot;God is spirit, and those who worship Him must worship in spirit and truth.&quot;
NASB John 4:25 The woman *said to Him, &quot;I know that Messiah is coming (He who is called Christ); when that One comes, He will declare all things to us.&quot;
NASB John 4:26 Jesus *said to her, &quot;I who speak to you am He.&quot;
NASB John 4:27 At this point His disciples came, and they were amazed that He had been speaking with a woman, yet no one said, &quot;What do You seek?&quot; or, &quot;Why do You speak with her?&quot;
NASB John 4:28 So the woman left her waterpot, and went into the city and *said to the men,</string></value></member>
  <member><name>post_parent</name><value><string>0</string></value></member>
  <member><name>post_mime_type</name><value><string></string></value></member>
  <member><name>link</name><value><string>http://www.splats-world.pw/?p=1900</string></value></member>
  <member><name>guid</name><value><string>http://www.splats-world.pw/?p=1900</string></value></member>
  <member><name>menu_order</name><value><int>0</int></value></member>
  <member><name>comment_status</name><value><string>closed</string></value></member>
  <member><name>ping_status</name><value><string>open</string></value></member>
  <member><name>sticky</name><value><boolean>0</boolean></value></member>
  <member><name>post_thumbnail</name><value><array><data>
</data></array></value></member>
  <member><name>post_format</name><value><string>standard</string></value></member>
  <member><name>terms</name><value><array><data>
</data></array>

Don't appear to have any preceding or trailing newlines in the data.

**Comment by kiwiheretic** [comment]
Ok, that failed miserably.  I put the xml file into this pastebin -> http://goo.gl/FGcBmx

**Comment by StevensUneven** [comment]
This is in no way a fix but just a workaround until it gets fixed but what I did to resolve this issue is open the xmlrpclib.py which is usually located in "C:\Python27\Lib\" at line 558 I changed `self._parser.Parse(data, 0 )` to `self._parser.Parse(data.strip(), 0 )`

**Comment by Strompf** [comment]
> This is in no way a fix but just a workaround until it gets fixed but what I did to resolve this issue is open the xmlrpclib.py which is usually located in "C:\Python27\Lib" at line 558 I changed `self._parser.Parse(data, 0 )` to `self._parser.Parse(data.strip(), 0 )`

That worked for me! Thank you!

**Comment by dlo** [comment]
I'm encountering this error with Python 3.7.2 and the latest version of the library. Not sure how to fix without monkey-patching this since the response and parsing functionality is all handled by Python itself.
