### ISSUE TITLE
<ProtocolError for mydomain.com/xmlrpc.php: 500 Internal Server Error>

### ISSUE THREAD

**Issue by djiesamsoe** [maxcutler/python-wordpress-xmlrpc#76]
I tried to make a post, but I found the error as follows:
```wordpress_xmlrpc.exceptions.ServerConnectionError: <ProtocolError for mydomain.com/xmlrpc.php: 500 Internal Server Error>```

errors that occur in my script as follows:
``` 
from wordpress_xmlrpc import Client
//error here
client = Client('http://mydomain.com/xmlrpc.php', 'username', 'password')
```

I asked for his help to resolve the issue.
Thanks before.

**Comment by maxcutler** [comment]
As the error message says, the issue is that your WordPress server is returning a 500 error code instead of a 200 with XML contents. You need to look at your server logs or manually send XML-RPC requests using curl or Postman or your tool of choice and see the actual error occuring on your server. If you need further help with your WordPress server configuration, https://wordpress.org/support/ is a more appropriate forum than my library's GitHub issues.

**Comment by djiesamsoe** [comment]
Thanks Max
