### ISSUE TITLE
Make tests run

### ISSUE THREAD

**Issue by balasankarc** [maxcutler/python-wordpress-xmlrpc#84]
Hi,
I am trying to package this module for Debian. Can we make the tests run successfully? Right now, it uses `mysite.com` which I assume is a filler URL. Also, wp-config-sample.cfg have to be renamed to wp-config.cfg for the tests to run.

I have a testing wordpress instance which we can use for this. The credentials are as follows
url = https://publish2wptesting.wordpress.com/xmlrpc.php
username = publish2wptest
password = publish2wptesting
userid = 89429663

Can we use them to make the tests run? It would be a great help.

**Comment by maxcutler** [comment]
It is dangerous to have WordPress site credentials published on the internet or in source control systems, since anyone who finds them can log into that site and use it for their own purposes (e.g., spam). This is why python-wordpress-xmlrpc requires a manual local step to configure the unit test suite.

Keep in mind that this library's test suite is really more integrating testing than unit testing, since it's making real calls to a WordPress site and verifying the behavior.

**Comment by balasankarc** [comment]
Oh. ok. For now, I will disable the tests.
